# Generated by Django 5.0.7 on 2024-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior')], default='JUNIOR', max_length=150),
        ),
    ]
