# Generated by Django 5.0.7 on 2024-07-30 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 7, 30, 11, 31, 56, 685427, tzinfo=datetime.timezone.utc), upload_to='images/category'),
            preserve_default=False,
        ),
    ]
